import type { UserProfile } from "../types";

export type MockUserRecord = UserProfile & { passwordHash: string };

export const DEFAULT_USERS: Record<string, MockUserRecord> = {
  "admin@estateportal.local": {
    id: "mock-admin-estate-portal",
    role: "admin",
    name: "Estate Portal Admin",
    email: "admin@estateportal.local",
    phoneNumber: "+1 (800) 555-0101",
    country: "Ethiopia",
    city: "Addis Ababa",
    company: "Estate Portal",
    professionalTitle: "Portal Administrator",
    avatarUrl: "https://ui-avatars.com/api/?name=Estate+Portal+Admin&background=f3ead8&color=775a19",
    preferredLanguage: "English (International)",
    currency: "USD ($)",
    emailNotifications: true,
    marketInsights: true,
    darkMode: false,
    totalAssets: "$0.0M",
    activeBuildCount: 0,
    passwordHash: "admin12345",
  },
  "mach10media.et@gmail.com": {
    id: "mock-user-alexander-vance",
    role: "client",
    name: "Alexander Vance",
    email: "mach10media.et@gmail.com",
    phoneNumber: "+1 (310) 555-0142",
    country: "Ethiopia",
    city: "Addis Ababa",
    company: "Mach10 Media",
    professionalTitle: "Principal Investment Architect",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    preferredLanguage: "English (International)",
    currency: "USD ($)",
    emailNotifications: true,
    marketInsights: true,
    darkMode: false,
    totalAssets: "$42.8M",
    activeBuildCount: 4,
    passwordHash: "password123",
  },
  "alex.vance@luxuryestates.com": {
    id: "mock-user-alex-vance",
    role: "client",
    name: "Alexander Vance",
    email: "alex.vance@luxuryestates.com",
    phoneNumber: "+1 (310) 555-0142",
    country: "Ethiopia",
    city: "Addis Ababa",
    company: "Luxury Estates",
    professionalTitle: "Principal Investment Architect",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&auto=format&fit=crop",
    preferredLanguage: "English (International)",
    currency: "USD ($)",
    emailNotifications: true,
    marketInsights: true,
    darkMode: false,
    totalAssets: "$42.8M",
    activeBuildCount: 4,
    passwordHash: "password123",
  },
  "sterling@aurelian.com": {
    id: "mock-user-sterling",
    role: "client",
    name: "Mr. Sterling",
    email: "sterling@aurelian.com",
    phoneNumber: "+1 (212) 555-0198",
    country: "Ethiopia",
    city: "Addis Ababa",
    company: "Aurelian Capital",
    professionalTitle: "Managing General Partner",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=150&auto=format&fit=crop",
    preferredLanguage: "English (International)",
    currency: "USD ($)",
    emailNotifications: true,
    marketInsights: false,
    darkMode: false,
    totalAssets: "$118.4M",
    activeBuildCount: 5,
    passwordHash: "sterling77",
  },
};
